---
- name: copy alertmanager config
  template:
    force: true
    src: "{{ alertmanager_config_file }}"
    dest: "{{ alertmanager_config_dir }}/alertmanager.yml"
    owner: alertmanager
    group: alertmanager
    mode: 0644
    validate: "/usr/local/bin/amtool --alertmanager.url=  check-config %s"
  notify:
    - restart alertmanager
